In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
import open3d as o3d
from torch.utils.data import Dataset, DataLoader, Subset
from dataclasses import dataclass
import sys
from pathlib import Path
from pytorch3d.loss import chamfer_distance
from tqdm import tqdm

sys.path.append(str(Path.cwd().parent))

import AutoEncoder.autoencoders as ae
from AutoEncoder.encoder import PointCloudAutoEncoder
from Helpers.data import PointCloudDataset
import Helpers.PointCloudOpen3d as pc
from Helpers.nsdf_live_sampler import sample_sdf
from SignDistanceModel.sdf_models import SDFRegressionModel

if torch.cuda.is_available():
    device = "cuda"

elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

print(f'Using: {device}')


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
Failed to sample sdf on file:  ./Data/vdbs/airplane/train/airplane_0001.vdb
Using: cuda


In [2]:
train_dataset_1024 = PointCloudDataset("../Data/ModelNet40", 1024, 'train', object_classes =  None )
test_dataset_1024 = PointCloudDataset("../Data/ModelNet40", 1024, 'test', object_classes =  None)

test_size = len(test_dataset_1024)
split_idx = test_size // 2
indices = list(range(test_size))
val_dataset_1024 = Subset(test_dataset_1024, indices[:split_idx])
test_dataset_1024 = Subset(test_dataset_1024, indices[split_idx:])

train_loader_1024= DataLoader(train_dataset_1024, batch_size = 64, shuffle = True)
val_loader_1024 = DataLoader(val_dataset_1024, batch_size = 128, shuffle = False)
test_loader_1024 = DataLoader(test_dataset_1024, batch_size = 128, shuffle = False)

/home/amuseth/dev/src/Neural-Sign-Distance-Learning/Helpers/data.py:69: RuntimeWarning: invalid value encountered in divide
  scaled_points = ((points - min_coords) / range_coords) #scales points on range [0, 1]
/home/amuseth/dev/src/Neural-Sign-Distance-Learning/Helpers/data.py:70: RuntimeWarning: invalid value encountered in cast
  scaled_points = (scaled_points * (2**num_bits - 1)).astype(int) # scales points to [0, 2^num_bits]


In [3]:
# Load model
model = ae.ConvAE_6800T(1024, 256)
model.load_state_dict(torch.load('../Data/trained_autoencoders/1024_256/Conv_6800T', weights_only=True))
print(model.to('cpu'))
model = model.to('cpu')

ConvAE_6800T(
  (encoder): ConvEncoder_6800T(
    (conv1): Conv1d(3, 32, kernel_size=(1,), stride=(1,))
    (conv2): Conv1d(32, 32, kernel_size=(9,), stride=(1,), padding=(4,))
    (conv3): Conv1d(32, 32, kernel_size=(9,), stride=(1,), padding=(4,))
    (conv4): Conv1d(32, 16, kernel_size=(8,), stride=(2,), padding=(3,))
    (conv5): Conv1d(16, 16, kernel_size=(8,), stride=(2,), padding=(3,))
    (conv6): Conv1d(16, 16, kernel_size=(8,), stride=(2,), padding=(3,))
    (lin1): Linear(in_features=2048, out_features=1024, bias=True)
    (lin2): Linear(in_features=1024, out_features=256, bias=True)
  )
  (decoder): ConvDecoder(
    (l1): Linear(in_features=256, out_features=1024, bias=True)
    (l2): Linear(in_features=1024, out_features=2048, bias=True)
    (l3): Linear(in_features=2048, out_features=3072, bias=True)
    (l4): Linear(in_features=3072, out_features=3072, bias=True)
  )
)


In [4]:
def visualize_random_reconstruction(model, x, device, transpose_out = False, show_org = True):
    '''
    Pick a random cloud from the dataset and show what it looks like before and after autoencoder reconstruction 
    First window is original point cloud 
    Second window is recontructed point cloud
    '''

    def show_cloud(x):
        pc.visualize_point_cloud(pc.get_point_cloud(x.cpu().numpy().astype(np.float64)))

    
    if show_org:
        show_cloud(x)

    with torch.no_grad():
        x = x.unsqueeze(0).permute(0,2,1).to(device)
        
        rec_x = model(x)[0].to('cpu')
        
        if transpose_out:
            rec_x = rec_x.T
        
        rec_x = rec_x

        show_cloud(rec_x)

#visualize_random_reconstruction(model, x, device)

In [ ]:
x = next(iter(val_loader_1024))
visualize_random_reconstruction(model, x['points'][0].to('cpu'), 'cpu')
print(x["filename"][0])

../Data/ModelNet40/sofa/test/sofa_0706.off


In [15]:
def train_one_mesh(filename, model, neural_encoding, optimizer, live_sampling=True, num_points=10000, num_epochs = 10000):
    train_losses = []
    val_losses = []
    criterion = nn.MSELoss()
    filename_split = filename.split('/')
    filename_split[2] = "vdbs"
    filename_split[-1]  = filename_split[-1][:-3] + "vdb" 
    vdb_filename = "".join([i + '/' for i in filename_split])[:-1]
    neural_encoding = neural_encoding.repeat(num_points, 1)
    for epoch in tqdm(range(num_epochs)):
        points, labels = sample_sdf(vdb_filename, num_points, device=device)
        perm = torch.randperm(num_points)
        points, labels = points[perm], labels[perm]
        optimizer.zero_grad()
        outputs = model(points, neural_encoding)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        if(epoch % 1000 == 0):
           print(labels[0], outputs[0])
           label_signs = torch.sign(labels)
           output_signs = torch.sign(outputs)
           correct_signs = (label_signs == output_signs).sum().item()
           print(correct_signs)
           print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

In [13]:
x = next(iter(val_loader_1024))

In [14]:
y = x["points"][0].unsqueeze(0).permute(0,2,1).to(device)
model.to(device) 
with torch.no_grad():
    neural_encoding = model.encoder(y)
sdf_model = SDFRegressionModel(3, 256, 128)
sdf_model.to(device)
optimizer = optim.AdamW(sdf_model.parameters(), lr=0.0001)
print(neural_encoding.shape)
train_one_mesh(x['filename'][0], sdf_model, neural_encoding, optimizer)

torch.Size([1, 256])


  0%|          | 1/10000 [00:00<22:11,  7.51it/s]

tensor([0.9580], device='cuda:0') tensor([-0.1284], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [1/10000], Loss: 0.3742


  1%|          | 103/10000 [00:08<13:08, 12.56it/s]

tensor([1.0816], device='cuda:0') tensor([0.1237], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [101/10000], Loss: 0.3168


  2%|▏         | 203/10000 [00:17<13:02, 12.52it/s]

tensor([0.8803], device='cuda:0') tensor([0.1337], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [201/10000], Loss: 0.3150


  3%|▎         | 301/10000 [00:25<13:04, 12.36it/s]

tensor([0.1186], device='cuda:0') tensor([0.1655], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [301/10000], Loss: 0.3138


  4%|▍         | 403/10000 [00:34<14:45, 10.83it/s]

tensor([0.8198], device='cuda:0') tensor([0.0665], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [401/10000], Loss: 0.3125


  5%|▌         | 503/10000 [00:43<13:28, 11.75it/s]

tensor([-0.2664], device='cuda:0') tensor([0.2220], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [501/10000], Loss: 0.3108


  6%|▌         | 603/10000 [00:51<13:42, 11.42it/s]

tensor([-0.4812], device='cuda:0') tensor([0.1157], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [601/10000], Loss: 0.3087


  7%|▋         | 703/10000 [01:00<12:29, 12.41it/s]

tensor([-0.5060], device='cuda:0') tensor([0.1963], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [701/10000], Loss: 0.3060


  8%|▊         | 803/10000 [01:08<12:37, 12.14it/s]

tensor([-0.5565], device='cuda:0') tensor([0.1630], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [801/10000], Loss: 0.3018


  9%|▉         | 903/10000 [01:17<12:08, 12.49it/s]

tensor([0.0778], device='cuda:0') tensor([0.0351], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [901/10000], Loss: 0.2956


 10%|█         | 1003/10000 [01:25<11:54, 12.58it/s]

tensor([0.3868], device='cuda:0') tensor([0.1275], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [1001/10000], Loss: 0.2878


 11%|█         | 1101/10000 [01:33<11:51, 12.51it/s]

tensor([-0.0307], device='cuda:0') tensor([0.0761], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [1101/10000], Loss: 0.2795


 12%|█▏        | 1203/10000 [01:42<13:00, 11.27it/s]

tensor([-0.3927], device='cuda:0') tensor([0.1384], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [1201/10000], Loss: 0.2711


 13%|█▎        | 1303/10000 [01:50<12:27, 11.63it/s]

tensor([-0.5432], device='cuda:0') tensor([-0.1204], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [1301/10000], Loss: 0.2630


 14%|█▍        | 1403/10000 [01:59<12:09, 11.78it/s]

tensor([-0.6047], device='cuda:0') tensor([-0.0215], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [1401/10000], Loss: 0.2554


 15%|█▌        | 1503/10000 [02:07<11:57, 11.84it/s]

tensor([-0.2747], device='cuda:0') tensor([-0.2167], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [1501/10000], Loss: 0.2478


 16%|█▌        | 1603/10000 [02:16<10:53, 12.84it/s]

tensor([-0.5218], device='cuda:0') tensor([-0.0240], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [1601/10000], Loss: 0.2409


 17%|█▋        | 1703/10000 [02:24<11:05, 12.47it/s]

tensor([1.1304], device='cuda:0') tensor([0.0567], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [1701/10000], Loss: 0.2344


 18%|█▊        | 1803/10000 [02:32<10:34, 12.93it/s]

tensor([-0.2478], device='cuda:0') tensor([0.0939], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [1801/10000], Loss: 0.2287


 19%|█▉        | 1901/10000 [02:40<11:15, 11.98it/s]

tensor([-0.4451], device='cuda:0') tensor([-0.2127], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [1901/10000], Loss: 0.2235


 20%|██        | 2003/10000 [02:49<12:19, 10.82it/s]

tensor([-0.1343], device='cuda:0') tensor([0.0753], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [2001/10000], Loss: 0.2191


 21%|██        | 2103/10000 [02:58<11:10, 11.78it/s]

tensor([0.0133], device='cuda:0') tensor([0.0313], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [2101/10000], Loss: 0.2151


 22%|██▏       | 2203/10000 [03:07<11:01, 11.79it/s]

tensor([-0.2493], device='cuda:0') tensor([0.1796], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [2201/10000], Loss: 0.2117


 23%|██▎       | 2303/10000 [03:15<10:04, 12.73it/s]

tensor([-0.3054], device='cuda:0') tensor([0.1056], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [2301/10000], Loss: 0.2085


 24%|██▍       | 2403/10000 [03:24<09:56, 12.74it/s]

tensor([-0.5501], device='cuda:0') tensor([-0.4322], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [2401/10000], Loss: 0.2055


 25%|██▌       | 2503/10000 [03:32<09:57, 12.54it/s]

tensor([-0.5942], device='cuda:0') tensor([-0.0048], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [2501/10000], Loss: 0.2029


 26%|██▌       | 2603/10000 [03:40<09:37, 12.81it/s]

tensor([0.9968], device='cuda:0') tensor([0.8629], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [2601/10000], Loss: 0.2004


 27%|██▋       | 2701/10000 [03:48<09:26, 12.87it/s]

tensor([0.8659], device='cuda:0') tensor([0.1103], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [2701/10000], Loss: 0.1980


 28%|██▊       | 2803/10000 [03:57<09:51, 12.17it/s]

tensor([-0.1270], device='cuda:0') tensor([0.1392], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [2801/10000], Loss: 0.1959


 29%|██▉       | 2903/10000 [04:05<10:20, 11.44it/s]

tensor([-0.5325], device='cuda:0') tensor([0.1009], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [2901/10000], Loss: 0.1938


 30%|███       | 3003/10000 [04:14<09:40, 12.06it/s]

tensor([-0.5213], device='cuda:0') tensor([-0.0825], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [3001/10000], Loss: 0.1919


 31%|███       | 3103/10000 [04:22<09:25, 12.19it/s]

tensor([-0.6041], device='cuda:0') tensor([-0.1087], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [3101/10000], Loss: 0.1901


 32%|███▏      | 3203/10000 [04:31<09:01, 12.55it/s]

tensor([-0.5500], device='cuda:0') tensor([0.1165], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [3201/10000], Loss: 0.1883


 33%|███▎      | 3303/10000 [04:39<08:47, 12.70it/s]

tensor([-0.1659], device='cuda:0') tensor([0.1491], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [3301/10000], Loss: 0.1868


 34%|███▍      | 3403/10000 [04:48<08:36, 12.78it/s]

tensor([-0.5505], device='cuda:0') tensor([-0.2676], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [3401/10000], Loss: 0.1851


 35%|███▌      | 3503/10000 [04:56<09:30, 11.38it/s]

tensor([0.7390], device='cuda:0') tensor([0.5308], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [3501/10000], Loss: 0.1835


 36%|███▌      | 3603/10000 [05:05<09:11, 11.61it/s]

tensor([-0.2968], device='cuda:0') tensor([-0.4010], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [3601/10000], Loss: 0.1820


 37%|███▋      | 3703/10000 [05:13<08:47, 11.95it/s]

tensor([1.1237], device='cuda:0') tensor([0.6038], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [3701/10000], Loss: 0.1805


 38%|███▊      | 3803/10000 [05:21<08:18, 12.44it/s]

tensor([0.1892], device='cuda:0') tensor([0.0773], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [3801/10000], Loss: 0.1790


 39%|███▉      | 3903/10000 [05:30<08:29, 11.97it/s]

tensor([-0.4116], device='cuda:0') tensor([-0.1522], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [3901/10000], Loss: 0.1777


 40%|████      | 4003/10000 [05:38<07:52, 12.69it/s]

tensor([0.2789], device='cuda:0') tensor([-0.0815], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [4001/10000], Loss: 0.1765


 41%|████      | 4103/10000 [05:47<07:44, 12.71it/s]

tensor([-0.2292], device='cuda:0') tensor([0.2552], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [4101/10000], Loss: 0.1753


 42%|████▏     | 4201/10000 [05:55<08:02, 12.02it/s]

tensor([0.2137], device='cuda:0') tensor([0.2586], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [4201/10000], Loss: 0.1740


 43%|████▎     | 4303/10000 [06:04<08:48, 10.78it/s]

tensor([-0.2882], device='cuda:0') tensor([-0.1291], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [4301/10000], Loss: 0.1727


 44%|████▍     | 4403/10000 [06:13<08:18, 11.23it/s]

tensor([0.3654], device='cuda:0') tensor([0.3407], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [4401/10000], Loss: 0.1716


 45%|████▌     | 4503/10000 [06:22<08:05, 11.32it/s]

tensor([1.1269], device='cuda:0') tensor([0.2339], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [4501/10000], Loss: 0.1704


 46%|████▌     | 4603/10000 [06:30<07:27, 12.07it/s]

tensor([-0.4168], device='cuda:0') tensor([-0.2348], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [4601/10000], Loss: 0.1693


 47%|████▋     | 4703/10000 [06:39<07:26, 11.87it/s]

tensor([-0.0425], device='cuda:0') tensor([0.0700], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [4701/10000], Loss: 0.1683


 48%|████▊     | 4803/10000 [06:48<06:55, 12.51it/s]

tensor([0.2569], device='cuda:0') tensor([0.2373], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [4801/10000], Loss: 0.1673


 49%|████▉     | 4903/10000 [06:56<06:45, 12.57it/s]

tensor([-0.2935], device='cuda:0') tensor([-0.1023], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [4901/10000], Loss: 0.1664


 50%|█████     | 5001/10000 [07:04<06:38, 12.54it/s]

tensor([-0.5224], device='cuda:0') tensor([-0.0597], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [5001/10000], Loss: 0.1654


 51%|█████     | 5103/10000 [07:13<07:11, 11.36it/s]

tensor([-0.1498], device='cuda:0') tensor([0.3259], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [5101/10000], Loss: 0.1645


 52%|█████▏    | 5203/10000 [07:21<06:57, 11.50it/s]

tensor([-0.0246], device='cuda:0') tensor([0.0729], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [5201/10000], Loss: 0.1636


 53%|█████▎    | 5303/10000 [07:30<06:33, 11.95it/s]

tensor([-0.6434], device='cuda:0') tensor([-0.2336], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [5301/10000], Loss: 0.1627


 54%|█████▍    | 5403/10000 [07:38<06:09, 12.44it/s]

tensor([0.6422], device='cuda:0') tensor([0.4906], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [5401/10000], Loss: 0.1619


 55%|█████▌    | 5503/10000 [07:46<06:05, 12.29it/s]

tensor([-0.4869], device='cuda:0') tensor([-0.4423], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [5501/10000], Loss: 0.1612


 56%|█████▌    | 5603/10000 [07:55<05:54, 12.39it/s]

tensor([-0.4689], device='cuda:0') tensor([0.2239], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [5601/10000], Loss: 0.1604


 57%|█████▋    | 5703/10000 [08:03<05:37, 12.74it/s]

tensor([0.6944], device='cuda:0') tensor([0.2881], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [5701/10000], Loss: 0.1598


 58%|█████▊    | 5803/10000 [08:12<06:02, 11.58it/s]

tensor([-0.2986], device='cuda:0') tensor([-0.0441], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [5801/10000], Loss: 0.1589


 59%|█████▉    | 5903/10000 [08:20<05:59, 11.38it/s]

tensor([-0.1364], device='cuda:0') tensor([-0.1177], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [5901/10000], Loss: 0.1582


 60%|██████    | 6003/10000 [08:28<05:37, 11.85it/s]

tensor([1.1073], device='cuda:0') tensor([0.9201], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [6001/10000], Loss: 0.1574


 61%|██████    | 6103/10000 [08:36<05:19, 12.18it/s]

tensor([0.8224], device='cuda:0') tensor([0.6289], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [6101/10000], Loss: 0.1567


 62%|██████▏   | 6203/10000 [08:45<05:11, 12.20it/s]

tensor([-0.4423], device='cuda:0') tensor([-0.2799], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [6201/10000], Loss: 0.1562


 63%|██████▎   | 6303/10000 [08:53<04:54, 12.56it/s]

tensor([0.5904], device='cuda:0') tensor([-0.0689], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [6301/10000], Loss: 0.1552


 64%|██████▍   | 6403/10000 [09:01<04:45, 12.60it/s]

tensor([-0.2076], device='cuda:0') tensor([-0.1818], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [6401/10000], Loss: 0.1546


 65%|██████▌   | 6501/10000 [09:10<04:37, 12.60it/s]

tensor([-0.5811], device='cuda:0') tensor([-0.2027], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [6501/10000], Loss: 0.1540


 66%|██████▌   | 6601/10000 [09:18<04:23, 12.88it/s]

tensor([-0.4433], device='cuda:0') tensor([-0.2526], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [6601/10000], Loss: 0.1534


 67%|██████▋   | 6703/10000 [09:27<04:40, 11.76it/s]

tensor([-0.4776], device='cuda:0') tensor([-0.2713], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [6701/10000], Loss: 0.1529


 68%|██████▊   | 6803/10000 [09:35<04:35, 11.62it/s]

tensor([-0.5334], device='cuda:0') tensor([-0.4180], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [6801/10000], Loss: 0.1524


 69%|██████▉   | 6903/10000 [09:43<04:16, 12.07it/s]

tensor([0.3743], device='cuda:0') tensor([0.1354], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [6901/10000], Loss: 0.1518


 70%|███████   | 7003/10000 [09:52<04:09, 12.04it/s]

tensor([1.0187], device='cuda:0') tensor([0.6998], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [7001/10000], Loss: 0.1510


 71%|███████   | 7103/10000 [10:00<03:56, 12.24it/s]

tensor([-0.0625], device='cuda:0') tensor([0.0659], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [7101/10000], Loss: 0.1505


 72%|███████▏  | 7203/10000 [10:09<03:37, 12.85it/s]

tensor([0.0550], device='cuda:0') tensor([-0.0889], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [7201/10000], Loss: 0.1501


 73%|███████▎  | 7303/10000 [10:17<03:33, 12.61it/s]

tensor([-0.2350], device='cuda:0') tensor([-0.0735], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [7301/10000], Loss: 0.1495


 74%|███████▍  | 7403/10000 [10:25<04:03, 10.67it/s]

tensor([0.1714], device='cuda:0') tensor([0.3203], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [7401/10000], Loss: 0.1488


 75%|███████▌  | 7503/10000 [10:34<03:38, 11.44it/s]

tensor([0.9719], device='cuda:0') tensor([0.3269], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [7501/10000], Loss: 0.1486


 76%|███████▌  | 7603/10000 [10:42<03:16, 12.22it/s]

tensor([-0.2356], device='cuda:0') tensor([-0.0808], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [7601/10000], Loss: 0.1479


 77%|███████▋  | 7703/10000 [10:50<03:09, 12.09it/s]

tensor([-0.2334], device='cuda:0') tensor([-0.3719], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [7701/10000], Loss: 0.1475


 78%|███████▊  | 7803/10000 [10:59<02:59, 12.25it/s]

tensor([-0.6478], device='cuda:0') tensor([-0.6698], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [7801/10000], Loss: 0.1469


 79%|███████▉  | 7903/10000 [11:07<02:44, 12.75it/s]

tensor([-0.3329], device='cuda:0') tensor([0.0381], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [7901/10000], Loss: 0.1465


 80%|████████  | 8003/10000 [11:16<02:35, 12.81it/s]

tensor([-0.5033], device='cuda:0') tensor([-0.1609], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [8001/10000], Loss: 0.1459


 81%|████████  | 8101/10000 [11:24<02:29, 12.67it/s]

tensor([-0.5309], device='cuda:0') tensor([-0.3943], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [8101/10000], Loss: 0.1456


 82%|████████▏ | 8203/10000 [11:33<02:45, 10.89it/s]

tensor([0.9321], device='cuda:0') tensor([0.1681], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [8201/10000], Loss: 0.1449


 83%|████████▎ | 8303/10000 [11:41<02:25, 11.66it/s]

tensor([0.3319], device='cuda:0') tensor([0.0124], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [8301/10000], Loss: 0.1447


 84%|████████▍ | 8403/10000 [11:49<02:10, 12.27it/s]

tensor([-0.5766], device='cuda:0') tensor([-0.1266], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [8401/10000], Loss: 0.1439


 85%|████████▌ | 8503/10000 [11:58<02:01, 12.35it/s]

tensor([0.9562], device='cuda:0') tensor([0.5226], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [8501/10000], Loss: 0.1438


 86%|████████▌ | 8603/10000 [12:06<01:50, 12.63it/s]

tensor([-0.5405], device='cuda:0') tensor([-0.5432], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [8601/10000], Loss: 0.1431


 87%|████████▋ | 8703/10000 [12:15<01:47, 12.02it/s]

tensor([0.3240], device='cuda:0') tensor([-0.0188], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [8701/10000], Loss: 0.1428


 88%|████████▊ | 8803/10000 [12:23<01:37, 12.32it/s]

tensor([-0.5389], device='cuda:0') tensor([-0.3231], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [8801/10000], Loss: 0.1424


 89%|████████▉ | 8901/10000 [12:31<01:26, 12.77it/s]

tensor([1.0844], device='cuda:0') tensor([0.0815], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [8901/10000], Loss: 0.1419


 90%|█████████ | 9003/10000 [12:40<01:28, 11.26it/s]

tensor([-0.5874], device='cuda:0') tensor([-0.3105], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [9001/10000], Loss: 0.1413


 91%|█████████ | 9103/10000 [12:48<01:19, 11.25it/s]

tensor([-0.1160], device='cuda:0') tensor([-0.1417], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [9101/10000], Loss: 0.1412


 92%|█████████▏| 9203/10000 [12:57<01:05, 12.19it/s]

tensor([0.1138], device='cuda:0') tensor([0.3066], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [9201/10000], Loss: 0.1405


 93%|█████████▎| 9303/10000 [13:05<00:56, 12.44it/s]

tensor([0.6970], device='cuda:0') tensor([0.5932], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [9301/10000], Loss: 0.1403


 94%|█████████▍| 9403/10000 [13:13<00:47, 12.60it/s]

tensor([0.4672], device='cuda:0') tensor([-0.0882], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [9401/10000], Loss: 0.1397


 95%|█████████▌| 9503/10000 [13:22<00:39, 12.57it/s]

tensor([0.7255], device='cuda:0') tensor([0.5943], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [9501/10000], Loss: 0.1395


 96%|█████████▌| 9603/10000 [13:30<00:31, 12.64it/s]

tensor([0.5967], device='cuda:0') tensor([0.6104], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [9601/10000], Loss: 0.1389


 97%|█████████▋| 9703/10000 [13:38<00:27, 10.83it/s]

tensor([-0.5736], device='cuda:0') tensor([-0.1033], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [9701/10000], Loss: 0.1387


 98%|█████████▊| 9803/10000 [13:47<00:18, 10.93it/s]

tensor([-0.5218], device='cuda:0') tensor([-0.1341], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [9801/10000], Loss: 0.1382


 99%|█████████▉| 9903/10000 [13:55<00:07, 12.19it/s]

tensor([0.8779], device='cuda:0') tensor([0.1265], device='cuda:0', grad_fn=<SelectBackward0>)
Epoch [9901/10000], Loss: 0.1379


100%|██████████| 10000/10000 [14:03<00:00, 11.85it/s]


In [16]:
train_one_mesh(x['filename'][0], sdf_model, neural_encoding, optimizer)

  0%|          | 2/10000 [00:00<14:38, 11.38it/s]

tensor([-0.3270], device='cuda:0') tensor([0.1707], device='cuda:0', grad_fn=<SelectBackward0>)
7891
Epoch [1/10000], Loss: 0.1373


 10%|█         | 1002/10000 [01:23<12:03, 12.44it/s]

tensor([-0.1702], device='cuda:0') tensor([0.2981], device='cuda:0', grad_fn=<SelectBackward0>)
7966
Epoch [1001/10000], Loss: 0.1340


 20%|██        | 2002/10000 [02:47<10:29, 12.71it/s]

tensor([1.0400], device='cuda:0') tensor([0.4601], device='cuda:0', grad_fn=<SelectBackward0>)
8028
Epoch [2001/10000], Loss: 0.1311


 30%|███       | 3002/10000 [04:11<10:03, 11.59it/s]

tensor([0.2116], device='cuda:0') tensor([0.2077], device='cuda:0', grad_fn=<SelectBackward0>)
7989
Epoch [3001/10000], Loss: 0.1284


 40%|████      | 4002/10000 [05:36<08:10, 12.23it/s]

tensor([-0.5531], device='cuda:0') tensor([0.1599], device='cuda:0', grad_fn=<SelectBackward0>)
7992
Epoch [4001/10000], Loss: 0.1263


 50%|█████     | 5002/10000 [07:00<06:42, 12.41it/s]

tensor([0.6680], device='cuda:0') tensor([0.8060], device='cuda:0', grad_fn=<SelectBackward0>)
8098
Epoch [5001/10000], Loss: 0.1238


 60%|██████    | 6002/10000 [08:24<05:54, 11.27it/s]

tensor([0.2920], device='cuda:0') tensor([0.4891], device='cuda:0', grad_fn=<SelectBackward0>)
8079
Epoch [6001/10000], Loss: 0.1220


 70%|███████   | 7002/10000 [09:49<04:17, 11.66it/s]

tensor([-0.3597], device='cuda:0') tensor([-0.0326], device='cuda:0', grad_fn=<SelectBackward0>)
8145
Epoch [7001/10000], Loss: 0.1200


 80%|████████  | 8002/10000 [11:13<02:41, 12.40it/s]

tensor([-0.5703], device='cuda:0') tensor([0.1685], device='cuda:0', grad_fn=<SelectBackward0>)
8190
Epoch [8001/10000], Loss: 0.1186


 90%|█████████ | 9002/10000 [12:39<01:20, 12.46it/s]

tensor([-0.4740], device='cuda:0') tensor([-0.3804], device='cuda:0', grad_fn=<SelectBackward0>)
8145
Epoch [9001/10000], Loss: 0.1172


100%|██████████| 10000/10000 [14:03<00:00, 11.86it/s]


In [18]:
y = x["points"][0].unsqueeze(0).permute(0,2,1).to(device)
model.to(device) 
with torch.no_grad():
    neural_encoding = model.encoder(y)
sdf_model2 = SDFRegressionModel(3, 256, 128)
sdf_model2.to(device)
optimizer = optim.AdamW(sdf_model2.parameters(), lr=0.001)
print(neural_encoding.shape)
train_one_mesh(x['filename'][0], sdf_model2, neural_encoding, optimizer, num_epochs = 100000)

torch.Size([1, 256])


  0%|          | 3/100000 [00:00<3:12:41,  8.65it/s]

tensor([0.9908], device='cuda:0') tensor([-0.0876], device='cuda:0', grad_fn=<SelectBackward0>)
4817
Epoch [1/100000], Loss: 0.3476


  0%|          | 23/100000 [00:02<2:59:42,  9.27it/s]


KeyboardInterrupt: 